services:
    kenzi_oro_commerce.controller.connect:
        class: Kenzi\OroCommerceBundle\Controller\ConnectController
        arguments:
            $configManager: '@oro_config.manager'
            $doctrine: '@doctrine'
            $aclHelper: '@oro_security.acl_helper'
        tags:
            - { name: controller.service_arguments }

    kenzi_oro_commerce.layout.data_provider.widget:
        class: Kenzi\OroCommerceBundle\Layout\DataProvider\WidgetDataProvider
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: layout.data_provider, alias: kenzi_widget }

    kenzi_oro_commerce.serializer.order_payload:
        class: Kenzi\OroCommerceBundle\Serializer\OrderPayloadSerializer

    kenzi_oro_commerce.webhook.dispatcher:
        class: Kenzi\OroCommerceBundle\Webhook\WebhookDispatcher
        arguments:
            $httpClient: '@http_client'
            $configManager: '@oro_config.manager'
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: kenzi_oro_commerce }

    kenzi_oro_commerce.event_listener.order_checkout:
        class: Kenzi\OroCommerceBundle\EventListener\OrderCheckoutListener
        arguments:
            $dispatcher: '@kenzi_oro_commerce.webhook.dispatcher'
            $serializer: '@kenzi_oro_commerce.serializer.order_payload'
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: kenzi_oro_commerce }
            - { name: kernel.event_listener, event: extendable_action.finish_checkout, method: onFinishCheckout, priority: -10 }

    kenzi_oro_commerce.event_listener.order_update:
        class: Kenzi\OroCommerceBundle\EventListener\OrderUpdateListener
        arguments:
            $dispatcher: '@kenzi_oro_commerce.webhook.dispatcher'
            $serializer: '@kenzi_oro_commerce.serializer.order_payload'
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: kenzi_oro_commerce }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\OrderBundle\Entity\Order', event: postUpdate }
