system_configuration:
    groups:
        kenzi:
            title: kenzi_oro_commerce.system_configuration.groups.kenzi.title
            icon: fa-comments
        kenzi_connection:
            title: kenzi_oro_commerce.system_configuration.groups.kenzi_connection.title
        kenzi_connection_website:
            title: kenzi_oro_commerce.system_configuration.groups.kenzi_connection.title

    fields:
        kenzi_oro_commerce.connect_button:
            ui_only: true
            data_type: string
            type: Kenzi\OroCommerceBundle\Form\Type\KenziConnectButtonType
            priority: 30
            options:
                label: kenzi_oro_commerce.system_configuration.fields.connect_button.label
                required: false
                resettable: false
        kenzi_oro_commerce.widget_enabled:
            data_type: boolean
            type: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            priority: 20
            options:
                label: kenzi_oro_commerce.system_configuration.fields.widget_enabled.label
                tooltip: kenzi_oro_commerce.system_configuration.fields.widget_enabled.tooltip
                required: false
    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            kenzi:
                                priority: -100
                                children:
                                    kenzi_connection:
                                        children:
                                            - kenzi_oro_commerce.connect_button
                                            - kenzi_oro_commerce.widget_enabled
        website_configuration:
            commerce:
                children:
                    kenzi:
                        priority: 1000
                        children:
                            kenzi_connection:
                                children:
                                    kenzi_connection_website:
                                        children:
                                            - kenzi_oro_commerce.connect_button
                                            - kenzi_oro_commerce.widget_enabled
